### ISSUE TITLE
Add `escrow_broker`, `escrow_commission`, and `escrow_period` parameters to the configuration module

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/starnamed#63]
We want to be able to claim commission on escrow swaps of starnames for IOV tokens.  

The `escrow_broker` parameter is an address where commission will be sent.  The `escrow_commission` parameter is a decimal value between 0 and 1 that is the fraction of the price that gets sent to the broker.  The commission should be automatically sent to the broker on a successful swap. `escrow_period` should be used to set the expiration time of an escrow as `now + escrow_period` when an escrow is created.  `escrow_period` units should be consistent with other measures of time in the configuration parameters, eg `domain_renew_period`.

(In the future, the broker will be a wasm smart contract that will divide the commission between IOV SAS and validators, for example.  The parameters will migrate into the escrow module's comos-sdk params after we have the wasm smart contract.)

**Comment by LeCodeurDuDimanche** [comment]
@davepuchyr Shouldn't we let the user choose the deadline, but limit it to `now + escrow_period` rather than enforcing it ?

**Comment by davepuchyr** [comment]
> @davepuchyr Shouldn't we let the user choose the deadline, but limit it to `now + escrow_period` rather than enforcing it ?

Yes, good point.
